### ISSUE TITLE
[BUG] Get-PnPPage results in "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by MRLNDRS** [pnp/powershell#114]
### Reporting an Issue or Missing Feature
An unexpected error when executing a cmdlet

### Expected behavior 
I expected to receive the page object from "Get-PnPPage"

### Actual behavior 
I've got the following error:
`Get-PnPPage : Object reference not set to an instance of an object.`

![image](https://user-images.githubusercontent.com/77396417/104465978-f7838d00-55b4-11eb-8ca1-dc7f2321df39.png)

### Steps to reproduce behavior
Get-PnPPage -Identity "Home"

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 0.3.33

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

**Comment by LeonArmston** [comment]
Hi 

I've just tested with the new nightly build 0.3.34 and was able to retrieve the page object using the following commands (this command specifically targets /SitePages already so you do not need to enter SitePages at all).

```
Connect-PnPOnline -url "https://tenantname.sharepoint.com/sites/ThePerspective" -Credentials LeonDev

Get-PnPPage -Identity "The-future-of-air-traffic--safely-sharing-the-skies-with-drones.aspx"
Get-PnPPage -Identity "Home"
```

Can you upgrade and try again using similar commands (connect directly to the site of the page you want to retrieve)? Also does Get-PnPList return anything on the site?

**Comment by MRLNDRS** [comment]
Hi @LeonArmston 

I've just updated to the 0.3.34 however I'm still not able to retrieve objects.

I've also tried the Get-PnPList command, this works like a charm!

![image](https://user-images.githubusercontent.com/77396417/104487030-dfb80300-55cc-11eb-8d97-81c23440e230.png)

**Comment by LeonArmston** [comment]
Hi 

Strange it seems to work for me:

![image](https://user-images.githubusercontent.com/12968962/104487557-2ace1800-55c5-11eb-8e2d-fc36d0b1f116.png)

Does adding .aspx to the command work i.e. 

`Get-PnPPage -Identity "Home.aspx"`

Alternatively does the below command return your page and have you tried Get-PnPPage with any other pages?

`Get-PnPFolderItem -Identity "SitePages"`

**Comment by erwinvanhunen** [comment]
The moment you get an error, you can enter Get-PnPException to list more details which could help us determining where exactly the problem lies.

**Comment by MRLNDRS** [comment]
I've tried to add everything you both suggested:

With .aspx makes no difference
`Get-PnPPage` -Identity "Home.aspx"` 

Get-PnPFolderItem does work and returns my page. I've not tried it with other pages.
`Get-PnPFolderItem -Identity "SitePages"`

I've also run Get-PnPException after the Get-PnPPage to expand the error, see image below:

![image](https://user-images.githubusercontent.com/77396417/104492159-8a332480-55d3-11eb-99f7-4d10ffcc2d52.png)

Thanks alot for the effort so far.

**Comment by jansenbe** [comment]
@MRLNDRS : how are you authenticating to PowerShell? Can you try adding a page to the site you're using and see if you can read that one?

**Comment by MRLNDRS** [comment]
@jansenbe I'm authenticating using the following:

![image](https://user-images.githubusercontent.com/77396417/104504868-611a9000-55e3-11eb-9283-d9dc78a78bef.png)

**Comment by erwinvanhunen** [comment]
@jansenbe : FYI, internally that's using ACS Auth using the PnP Framework AuthManager.

**Comment by jansenbe** [comment]
I'll test that case tomorrow

**Comment by jansenbe** [comment]
I'm not able to reproduce when using ACS, not from source code and not from using PS

**Comment by MRLNDRS** [comment]
The issue still persists, anything else I can do to enhance the possibility to troubleshoot?

**Comment by jansenbe** [comment]
I'm suspecting that the page itself cannot be parsed by the page API...can you create a new page using the UI in that site and try to load that site?

**Comment by MRLNDRS** [comment]
Sure thing, just tried it. Same result:

![image](https://user-images.githubusercontent.com/77396417/104567975-bab8a400-564f-11eb-9657-9260a5e37f3d.png)

![image](https://user-images.githubusercontent.com/77396417/104567980-bd1afe00-564f-11eb-9ef6-0c9e831bda05.png)

**Comment by jansenbe** [comment]
would it be possible to setup a test site, configure Azure ACS for that site and share the clientid/secret/url with me so I can try to debug this. Also, what kind of permissions did you grant via ACS?

**Comment by MRLNDRS** [comment]
@jansenbe 

I've just setup a developer tenant and there seemed to be a problem regarding a connection using client id, client secret and url. 

I found some information on the following blog: https://www.koskila.net/literally-breaking-changes-to-app-authentication-on-sharepoint-%F0%9F%98%B5/

Well that fix feeled like a step backwards so i've now established a connection using a certificate
`Connect-PnPOnline -ClientId -CertificatePath -CertificatePassword -Url -Tenant`

Now Get-PnPPage is working like a charm, so it might be a mismatch with the way of authentication. I will setup the same certification connection on the production tenant and let you know wether this solves my problem there as well.

**Comment by MRLNDRS** [comment]
Unfortunately the issue persists on the original tenant.. I'm looking into sharing access.

**Comment by gautamdsheth** [comment]
Getting a different but maybe related error related to this. On the latest 3.39-nightly build, using the username/password  creds with PnP Mgt Shell Azure AD app installed.

Steps to repro - 

```
Connect-PnPOnline "<site-collection-url>"
$page = Get-PnPPage -Identity "page-name.aspx"
```

Error and the Get-PnPException message:

```
Get-PnPPage : Item has already been added. Key in dictionary: 'CorrelationId'  Key being added: 'CorrelationId'
At line:1 char:9
+ $page = Get-PnPPage -Identity "page.aspx"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PnPPage], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,PnP.PowerShell.Commands.Pages.GetPage
```

Am testing this on the old PowerShell, PS 5 the one with blue background.
Also, did a fiddler trace on this, there is no request at all !!

The one for Connect-PnPOnline is there, but no strangely no HTTP request for the Get-PnPPage method, so maybe some initialization logic issue ?

**Comment by jansenbe** [comment]
@gautamdsheth : so far I'm not able to reproduce this, for me this works in PS 5:
![image](https://user-images.githubusercontent.com/7451219/105029305-7b74c380-5a52-11eb-9926-f955465575ee.png)

**Comment by TGiersberg** [comment]
I have the same issue @MRLNDRS has got `Object reference not set to an instance of an object.`. PS 7, pnp module 1.1.0 using certificate based authentication.

![image](https://user-images.githubusercontent.com/77725352/105164362-55fcbe00-5b15-11eb-8475-a54e52c8bd2e.png)

**Comment by gautamdsheth** [comment]
@jansenbe - yeah, mine was a weird one. Got fixed after updating Az module to v5.4.0 , looks like some conflict with application insights DLL.

**Comment by jansenbe** [comment]
@TGiersberg , @MRLNDRS : I've just fixed an issue around loading pages from a non English site (see https://github.com/pnp/pnpcore/commit/dd43f2fa1943495449c0e517419666cc5049e45d)...are you also using the sites that show the issue in another language than English? 

The fix I created today will be included in the nightly PowerShell, PnP Framework and PnP Core SDK builds of tomorrow.

**Comment by MRLNDRS** [comment]
Been a short while, now updated to v1.1.2 and everything seems to be fixed! Thanks alot for the effort in investigating this!

**Comment by remandlo** [comment]
> Hi
> 
> I've just tested with the new nightly build 0.3.34 and was able to retrieve the page object using the following commands (this command specifically targets /SitePages already so you do not need to enter SitePages at all).
> 
> ```
> Connect-PnPOnline -url "https://tenantname.sharepoint.com/sites/ThePerspective" -Credentials LeonDev
> 
> Get-PnPPage -Identity "The-future-of-air-traffic--safely-sharing-the-skies-with-drones.aspx"
> Get-PnPPage -Identity "Home"
> ```
> 
> Can you upgrade and try again using similar commands (connect directly to the site of the page you want to retrieve)? Also does Get-PnPList return anything on the site?

Hi Leon

My page is in  <site>/SitePages/Templates/MyPage.aspx

I tried the following:
Get-PnPPage -Identity "MyPage.aspx"
Get-PnPPage -Identity "Templates/MyPage.aspx"
Get-PnPPage -Identity "/Templates/MyPage.aspx"

and I am still getting the error, Get-PnPPage: Object reference not set to an instance of an object.
