### ISSUE TITLE
[BUG] Set-PnPMicrosoft365Group throws 'Cannot access a disposed object'

### ISSUE THREAD

**Issue by timtatam** [pnp/powershell#1167]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Set-PnPMicrosoft365Group -Identity $siteDetails.GroupId -GroupLogoPath '.\customlogo.png' sets a new logo for the group

### Actual behavior 
```
Set-PnPMicrosoft365Group : Cannot access a disposed object.
Object name: 'System.Net.Http.ByteArrayContent'.
At line:1 char:1
+ Set-PnPMicrosoft365Group -Identity $siteDetails.GroupId -GroupLogoPat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-PnPMicrosoft365Group], ObjectDisposedException
    + FullyQualifiedErrorId : System.ObjectDisposedException,PnP.PowerShell.Commands.Microsoft365Groups.SetMicrosoft36
   5Group
```

### Steps to reproduce behavior
run the above cmdlet

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@timtatam - Can you try with the nightly release as I believe your issue #1155 (now resolved in the nightly release) was perhaps related?

**Comment by timtatam** [comment]
@veronicageek I did install the nighty 1.7.61, but I get the same issue :(

**Comment by gautamdsheth** [comment]
@timtatam - can't reproduce this issue ? Can you try with the latest nightly ? I uploaded both jpeg and png images. No errors and the logo is indeed uploaded

![image](https://user-images.githubusercontent.com/8832018/135678856-273280c9-9332-4b42-ac8a-024a6dc62238.png)

**Comment by timtatam** [comment]
@gautamdsheth I updated to nightly 1.7.68 and still have the same issue.
Which PS version do you use?
![image](https://user-images.githubusercontent.com/8087836/135819585-45ce91c5-c35f-4214-9e4a-eaa79a6afaae.png)

**Comment by timtatam** [comment]
@gautamdsheth ok, just installed PS 7.1 and ran the cmdlet there. Here I don't get any error, but the Group photo is not updated
![image](https://user-images.githubusercontent.com/8087836/135826798-06a137e1-d66b-4a62-96b6-407cb54c79a8.png)

Any ideas?

![image](https://user-images.githubusercontent.com/8087836/135825832-6c577322-4b10-4744-9cf3-bae7120aeecd.png)

**Comment by Dietrija** [comment]
I get the same problem: 
![image](https://user-images.githubusercontent.com/91937166/135971334-0d73c86c-b795-4c48-854e-fe4b6558c05b.png)

Here my PS version:
![image](https://user-images.githubusercontent.com/91937166/135971435-1b9213fc-4dca-427c-a4c8-fa91b005d884.png)

**Comment by gautamdsheth** [comment]
> @gautamdsheth ok, just installed PS 7.1 and ran the cmdlet there. Here I don't get any error, but the Group photo is not updated ![image](https://user-images.githubusercontent.com/8087836/135826798-06a137e1-d66b-4a62-96b6-407cb54c79a8.png)
> 
> Any ideas?
> 
> ![image](https://user-images.githubusercontent.com/8087836/135825832-6c577322-4b10-4744-9cf3-bae7120aeecd.png)

Yeah, it takes upto 24 hours for the change in image. We can't do anything about it because its just Graph API.
I use PS 5 in Win 10.

**Comment by gautamdsheth** [comment]
> I get the same problem: ![image](https://user-images.githubusercontent.com/91937166/135971334-0d73c86c-b795-4c48-854e-fe4b6558c05b.png)
> 
> Here my PS version: ![image](https://user-images.githubusercontent.com/91937166/135971435-1b9213fc-4dca-427c-a4c8-fa91b005d884.png)

Please try with the latest nightly build.

**Comment by timtatam** [comment]
@gautamdsheth just checked, the image is still the default one :(

**Comment by timtatam** [comment]
@gautamdsheth ok just realized that you need to be Owner of the Group to upload the picture. The app permission alone is not sufficient!
Bug can therefore be closed. Thanks for your help!

**Comment by Dietrija** [comment]
thanks @timtatam thats also explained why i got this errormessage. Now, after setting up the persmission correctly the cmdlet works!
