### ISSUE TITLE
[BUG] Add/Set-PnPListItem fails with "A possible object cycle was detected..." when updating date fields in batch mode

### ISSUE THREAD

**Issue by adzero** [pnp/powershell#1321]
### Reporting an Issue
Add-PnPListItem or Set-PnPListItem fails with "A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0" message when used to update some date fields (and maybe other types).
The error is not raised when not using batch mode. 
Problem first mentioned in another batch related  issue. (https://github.com/pnp/powershell/issues/1109)

### Expected behavior 
List item should be added or updated with provided date values.

### Actual behavior 
Command fails when providing Date field in Values parameter inside custom script.

### Steps to reproduce behavior

```
Connect-PnPOnline -Url $url -Credentials $credentials
$batch = New-PnPBatch
Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField=(get-date)} -Batch $batch
Invoke-PnpBatch -Batch $batch
```
ends with

```
Set-PnPListItem : A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0.
Au caractère Ligne:1 : 1
+ Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField=(get-date).ToUniversalTime()}  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], JsonException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem
```

![133965864-cdb7d93d-3302-4928-a616-54206f83ac97](https://user-images.githubusercontent.com/7522988/139877151-b25774ad-9744-4a5a-aaa8-1edcc4bfd813.png)

### What is the version of the Cmdlet module you are running?
Using the 1.8.0 version of PnP.PowerShell module. Error doesn't occur with 1.6.0 version.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@adzero - can you try with the latest nightly version and check ? We fixed some bugs related to list items.

**Comment by adzero** [comment]
@gautamdsheth - I tried the same lines with 1.8.39-nightly. 
List item is updated without errors with the following commands : 

`Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField=(get-date)} -Batch $batch`
or
`Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField=(get-date).ToUniversalTime()} -Batch $batch`

Error is still raised with : 

`Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField=$(get-date)} -Batch $batch`

Error is not raised but field is not updated after `Invoke-PnpBatch` with : 

`Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField="$((get-date).ToUniversalTime())"} -Batch $batch`

**Comment by gautamdsheth** [comment]
Have managed to fix the issue, it will be available in tomorrow's nightly !
Thanks for spotting the issue and raising it here :)
