### ISSUE TITLE
[BUG] Incorrect CompatiblePSEditions for 2.x in module manifest - remove "Desktop"

### ISSUE THREAD

**Issue by fowl2** [pnp/powershell#3170]
Version 2.x of this module doesn't support "Desktop" aka .NET Framework/non-"Core" based PowerShell editions. 

Therefore "Desktop" should be removed from the [`CompatiblePSEditions`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_editions#the-compatiblepseditions-module-manifest-field) field of the module metadata:

https://github.com/pnp/powershell/blob/c4d542c66413ce2a18487b4bac4a89cc515aad1b/build/Build-Debug.ps1#L150

(perhaps a different script is used for release builds, but I couldn't find it)

If there are further requirements on the minimum supported version of PowerShell, also consider setting [`PowerShellVersion`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_module_manifests#powershellversion).

This will prevent the module from being installed or imported, which is vast improvement on the rather inscrutable messages about files not being found we get otherwise.

Previously reported: https://github.com/pnp/powershell/issues/3121, https://github.com/pnp/powershell/discussions/3009, https://github.com/pnp/powershell/issues/2969, https://learn.microsoft.com/en-us/answers/questions/1196279/import-module-could-not-load-file-or-assembly-syst

**Comment by gautamdsheth** [comment]
Done, thanks @fowl2 !

**Comment by fowl2** [comment]
@gautamdsheth sorry but I don't think https://github.com/pnp/powershell/commit/d0e0dce03f98719b1f63d9aae272d457ec5b8c32 is quite enough - the [published module manifest](https://www.powershellgallery.com/packages/PnP.PowerShell/2.2.0/Content/PnP.PowerShell.psd1) is still missing `CompatiblePSEditions.
