### ISSUE TITLE
[BUG] Connect-PnpOnline -ManagedIdentity fails for ServiceConnection (AzureDevOps)

### ISSUE THREAD

**Issue by kkazala** [pnp/powershell#3249]
### Expected behavior 
I am deploying my SPFx solution using Azure DevOps pipeline. 
I have a **Service Connection** defined in the project, and the SPN has the following API permissions (I'm using `Sites.Selected` but for the sake of troubleshooting I granted `Sites.FullControl.All`) :
![image](https://github.com/pnp/powershell/assets/22429087/35495ac0-b4c4-4571-8950-acb4d7b1789d)

In the pipeline, I'm executing PowerShell code using the Service Connection: 
```yaml
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: "${{ parameters.serviceConnectionName }}"
            azurePowerShellVersion: LatestVersion
            ScriptType: 'InlineScript'
            Inline: |
              whoami
              Install-Module PnP.PowerShell -Scope "CurrentUser" -Verbose -AllowClobber -Force

              # TEST 1
              try{
                Connect-PnPOnline -ManagedIdentity -Url "https://$(Az_TenantName).sharepoint.com/sites/appcatalog/"
                Get-PnPConnection
              }
              catch{
                Write-Host "Error connecting to tenant app catalog"
                Write-Host $_.Exception.Message
              }
              # TEST 2
              try{
                $graphToken= Get-AzAccessToken -ResourceUrl "https://graph.microsoft.com/"
                Connect-PnPOnline -AccessToken  $graphToken -Url "https://$(Az_TenantName).sharepoint.com/sites/appcatalog/"
                Get-PnPConnection
              }
              catch{
                Write-Host "Error connecting to tenant app catalog"
                Write-Host $_.Exception.Message
              }
```

### Actual behavior 
TEST 1
`Connect-PnPOnline -ManagedIdentity` fails with the following error:
```ps
Error connecting to tenant app catalog
{"error":"invalid_request","error_description":"Identity not found"}
```

TEST 2
The `Connect-PnPOnline -AccessToken  $graphToken` works.

### Steps to reproduce behavior
1. Create a project in Azure DevOps
2. Create a Service Connection pointing to your Azure Subscrption
3. Go to "Project Settings" / "Service Connections". Choose the connection created in step 2 and click on "Manage Service Principal". Go to "API Permissions" and grant  `Sites.FullControl.All` Application permissions for Microsoft Graph and SharePoint.
4. Create a pipeline using the steps presented above, replacing `${{ parameters.serviceConnectionName }}` with your connection name and $(Az_TenantName) with your tenant name
5. Execute the pipeline

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : Azure DevOps MS agent,  `ubuntu-latest`

**Comment by kkazala** [comment]
No, my bad, I created connection using service principal authentication 🤦‍♀️
![image](https://github.com/pnp/powershell/assets/22429087/7176ea31-28bb-44df-809d-04a2bee1c140)

**Comment by kkazala** [comment]
Now that we can create Azure DevOps service connections using [workload identity federation](https://learn.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops), it would be really useful to be able to call `Connect-PnPOnline` from `AzurePowerShell@5` task and be able to execute within the context of the current identity. 

Would you be open to this idea?

**Comment by gautamdsheth** [comment]
Hello, we have implemented the Azure AD Workload identity based on this: https://azure.github.io/azure-workload-identity/docs/installation.html

Is it different compared to what you are using ? Also, do you have any reference to sample code on how we can get the access token ? Totally open to adding it here.

**Comment by kkazala** [comment]
@gautamdsheth 
Please have a look at my [post at dev.to](https://dev.to/kkazala/azure-devops-pipeline-with-workload-identity-federation-2gpj), where I describe what I'm doing step by step.

Bottomline: to sign in to SPO site I need to execute the following:
```powershell
 $azAccessToken = Get-AzAccessToken -ResourceUrl $url
 $conn = Connect-PnPOnline -Url "$url/sites/$(siteName)" -AccessToken $azAccessToken.Token -ReturnConnection

# and test using the returned connection as a parameter
 Add-PnPListItem -List "test" -Values @{"Title"="$(Build.BuildId)"} -Connection $conn       
```

Executing the `Connect-PnPOnline -Url $url -AzureADWorkloadIdentity` command give me an [error](https://github.com/pnp/powershell/issues/3476#issuecomment-1764244453)

**Comment by JakeStanger** [comment]
Confusingly, Workload Identity Federation seems to be different to Workload Identity - *Federation* is the new service principal auth method using OIDC, whereas WI just seems to be Kubernetes specific.

Would be very happy to be corrected on this, but [the docs](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#can-i-use-other-means-besides-certificates-for-realizing-app-only-access-for-my-azure-ad-app) and testing seems to indicate that SPO does not support Workload Identity Federation. It only supports certificate auth, and fails with HTTP 401 for tokens obtained with other auth types. This would make support in PnP PowerShell unfortunately rather limited.

**Comment by kkazala** [comment]
@JakeStanger  thx for looking into it. 
Yes, I noticed that the pipeline with Workload Identity Federation is creating a service principal. I wasn't sure if `AzureADWorkloadIdentity` would be the parameter to use in this case. I sometimes try things to find out =)
The Service Principal is good news, because we can now grant API permissions (I'm using `Sites.Selected` for Graph and SPO APIs) and grant access to a specific SPO site

_"It only supports certificate auth, and fails with HTTP 401 for tokens obtained with other auth types."_
One thing I'm sure is that my approach, as described above, works. I just executed the pipeline again and it still works today.
I think the key here is that I'm not really authenticating. I'm just refreshing the token 🙃Using `refresh_token` to exchange Azure/Graph token for a SPO token is not new anyway

So I guess the question is- where does it fit into the authentication model? 
It would be great if we could have it embedded in the pnp Powershell, instead of executing the above two lines separately. 

Can you conform that the example I included above works for you? And if yes, do you think we could have it supported  natively by PnP? Maybe another parameter?

**Comment by JakeStanger** [comment]
To clarify:
> "It only supports certificate auth, and fails with HTTP 401 for tokens obtained with other auth types."

This was only referring to the other *service principal* auth types, so client secret & WIF.

In your linked approach, you rely on the `AzurePowerShell` step which you pass the ARM connection into. Internally this must be obtaining the WIF token, which `Get-AzAccessToken` gets. I think you're then relying on an interesting quirk that enterprise apps can act as managed identities? That's a clever workaround, since managed identity auth to SPO works fine. 

With that extra knowledge, I'm on board with what you're saying. It would be ideal if DevOps and PnP.PowerShell integrated smoothly with the Managed Identity. I do wonder how feasibile that is to implement though? 

It would also be ideal, to provide a slightly less hacky approach in general support a wider range of scenarios, if the SPO guys gave us the ability to use WIF directly through a service principal, without any of the enterprise app faff. I appreciate that's out of scope for this though :)

**Comment by kkazala** [comment]
@JakeStanger lol, didn't notice the lack of "collaborator" tag next to your name and assumed you are part of the PnP team 🙈 Sorry about that 🤷🏻‍♀️

**Comment by JakeStanger** [comment]
No worries! I've just given it a go and it looks like it may actually be a lot simpler than we thought.

It looks like you don't need to worry about any of the enterprise app or managed identity stuff - I just granted permissions onto the normal old app registration through the portal, set up the WIF/ARM connection (as you'd expect, just copying values back/forth with the web interface) and it Just Werked:tm: I didn't even need to look at the Enterprise Application or run any scripts (other than the actual pipeline one).

You still need the workaround to use `Get-AzAccessToken` and pass that to Connect-PnPOnline, so there's definitely room for improvement there.

**Comment by gautamdsheth** [comment]
@JakeStanger / @kkazala   - Ahh Azure and naming 😂

So, what we implemented was something kubernetes specific. 
What this feature request is about is Workload Identity Federation.

@JakeStanger - can we reverse engineer/check how Az PowerShell obtains the tokens in WIF scenario ? Would be happy to include that here ? 
Also, this parameter, `-WorkloadIdentity`, since it is confusing, should we rename it or something ? We can do it since we haven't GA'ed this , would love to hear your thoughts on this.

**Comment by kkazala** [comment]
@JakeStanger  _"It looks like you don't need to worry about any of the enterprise app or managed identity stuff "_ 
about that... 
I actually want to "worry about it". Managed Identity is probably my favorite capability in Azure. It improves security of the solution and allows me to stop worrying about all of the app registration secrets/certificates stuff. ;)
So even though you can use my "hack" in a service connection configured with a service principal, this is not what my ticket is about (as @gautamdsheth correctly pointed out 👍) 

Do you think we should have yet another parameter, clearly pointing out it's AzureDevOps?

**Comment by JakeStanger** [comment]
> Also, this parameter, -WorkloadIdentity, since it is confusing, should we rename it or something ?

The more I look into this, the more confusing it gets. From [this page](https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation), I think what it's saying is that the whole thing is called Workload Identity Federation, and Workload Identity (the Kubernetes thing) is a supported scenario of that.

If it remains specific, you could rename it to `AksWorkflowIdentity` so it's clear it belongs to Azure Kubernetes Service. AKS definitely would need to be mentioned in any help/description text at least.

 It may actually work out, depending on implementation details, that you can support all scenarios in which case changing it to `WorkloadIdentityFederation` would probably make the most sense.

> It improves security of the solution and allows me to stop worrying about all of the app registration secrets/certificates stuff. ;)

@kkazala Using WIF effectively accomplishes the same thing - you can use it in place of secrets/certificates and don't need any credentials to perform the auth :) It arguably makes more sense in this context too, since Managed Identities are for resources within your Azure tenant, which the DevOps hosted agents technically are not. 

---

> can we reverse engineer/check how Az PowerShell obtains the tokens in WIF scenario ?

I can't see why not. So there's sorta two big steps in the process:

1. The `AzurePowerShell@5` DevOps step has the code responsible for creating the auth. It gets details from context and uses those to fetch a federated token, then passes that to Azure PowerShell in order to auth it. You can see in the logs this actually runs:
```powershell
Connect-AzAccount -ServicePrincipal -Tenant *** -ApplicationId *** -FederatedToken ***** -Environment AzureCloud -Scope Process
```
2. More relevant to us - It looks like `Get-AzAccessToken` eventually reaches out to the `Azure.Identity` credential helpers, requesting a token. It also rather helpfully caches tokens, so repeat calls returns the same token.

It may actually be relatively simple, and all that is required is to use the [AzurePowerShellCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.azurepowershellcredential?view=azure-dotnet) helper to get the cached token. 

If not there is also a [WorkloadIdentityCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.workloadidentitycredential?view=azure-dotnet) class.  That'll require a bit more reverse-engineering etc to get the context out from the current environment, and I *think* it might be Kubernetes-specific, but again not very clear.

Otherwise, PnP PowerShell could probably just support the auth flow itself. I think there's a very specific set of values you need to put in specific places along the way to make SPO auth work (Graph is easy...) but it's clearly possible. Getting a federated OIDC token out of DevOps would likely have to be a manual step, but that could then be passed to get a valid auth token:

https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow#third-case-access-token-request-with-a-federated-credential

**Comment by eduardpaul** [comment]
> Confusingly, Workload Identity Federation seems to be different to Workload Identity - _Federation_ is the new service principal auth method using OIDC, whereas WI just seems to be Kubernetes specific.
> 
> Would be very happy to be corrected on this, but [the docs](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#can-i-use-other-means-besides-certificates-for-realizing-app-only-access-for-my-azure-ad-app) and testing seems to indicate that SPO does not support Workload Indentity Federation. It only supports certificate auth, and fails with HTTP 401 for tokens obtained with other auth types. This would make support in PnP PowerShell unfortunately rather limited.

@JakeStanger thanks for the link to docs, it was really hard to understand why I could connect and read web props using the access token but, as soon as i try to install spfx solution I get the "The remote server returned an error: (401) Unauthorized.".

**Comment by gautamdsheth** [comment]
@kkazala - can you try with `Connect-PnPOonline -AzureADWorkloadIdentity` and let us know ?

**Comment by kkazala** [comment]
@gautamdsheth  I tried it [before](https://github.com/pnp/powershell/issues/3249#issuecomment-1765846491), and according to the documentation the `AzureADWorkloadIdentity` is for another case.

Am I correct that when signing in, you are using the same approach as Azure SDK for .NET? 
There's a ticket [AzurePipelinesCredential parameterless constructor and add to DAC](https://github.com/Azure/azure-sdk-for-net/issues/44969) about adding support for the Workload Identity Federation to the `DefaultAzureCredential`

Perhaps once it's done, you could simple use the same approach or, even better, add a `-DefaultAzureCredential` switch? =)
What do you think?

**Comment by gautamdsheth** [comment]
Took us some time, but we added the support for Federated Identity now. It is available starting with tomorrow's nightly builds. It would work like this:

`Connect-PnPOnline -Url "<URL>" -ClientId <ClientId> -Tenant <tenant> -FederatedIdentity`

Added support for both GH actions and Azure DevOps. Would love to hear your feedback on this.

**Comment by ryan-rosenburg** [comment]
When will this feature be available in the stable release?

**Comment by JakeStanger** [comment]
I have a project currently where I am aiming to use this, but I am not having any luck currently. When trying to connect inside a DevOps Pipelines job, I am getting an HTTP 400 back:

```
Connect-PnPOnline: /home/vsts/work/1/s/src/GenerateTemplate.ps1:8
Line |
   8 |      Connect-PnPOnline -Url $SiteUrl -ClientId $clientId -Tenant $tena …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed to retrieve access token with federated token: Response status
     | code does not indicate success: 400 (Bad Request).
```

The full line for completeness:

```pwsh
Connect-PnPOnline -Url $SiteUrl -ClientId $clientId -Tenant $tenantId -FederatedIdentity
```


The error stems from here in the code, indicating *something* went wrong getting the token:
https://github.com/pnp/powershell/blob/8b44f33a8e4fdd768ee8152efae1a8902264da07/src/Commands/Base/TokenHandler.cs#L408-L411

Although it's clear this comes from the `oauth2/v2.0/token` endpoint, ideally we need more information here.

The step in the pipeline below too:

```yaml
  - task: AzurePowerShell@5
    displayName: 'Generate Template'
    inputs:
      azureSubscription: $(serviceConnection)
      azurePowerShellVersion: LatestVersion
      pwsh: true
      scriptPath: $(Build.SourcesDirectory)/src/GenerateTemplate.ps1
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```

`Sites.FullControl.All` has been granted for both SPO and Graph resources as an application permission (as far as I know, awaiting definite confirmation from the client on this one).

**Comment by gautamdsheth** [comment]
@JakeStanger - thanks for trying this out. Can you maybe try with a simple cmdlet like `Get-PnPList` or something ? Hopefully that works ? Maybe there's some issue with the audience if using a template or something , something for us to fix for sure.

**Comment by JakeStanger** [comment]
Thanks for getting back to me. Although the script is intended to call the provisioning engine, it's failing at the auth step (`Connect-PnPOnline`) so it's not getting far enough in for that to be relevant, and I can't get as far as `Get-PnPList` or anything.

**Comment by gautamdsheth** [comment]
Hey @JakeStanger , sorry my bad. Looks like we had some additional encoding in place which caused this error. Should be fixed in tomorrow's nighty I think. Please let me know how it goes !

**Comment by JakeStanger** [comment]
Perfect, thanks for the quick turnaround. I should be able to confirm tomorrow, or Weds at the latest

**Comment by ryan-rosenburg** [comment]
@gautamdsheth When will this feature be available in the stable release?

**Comment by gautamdsheth** [comment]
@ryan-rosenburg - pretty soon. We don't have ETA at the moment though

**Comment by JakeStanger** [comment]
@mahajangaurav still not having any success I'm afraid, using the latest `3.1.70-nightly`. I'm getting the same 400 error.

Are we able to log the response body? This could be a configuration issue with the app reg for all I know, but I don't have any visibility into it.

**Comment by gautamdsheth** [comment]
@JakeStanger - have added code to log response body, should be there in tomorrow's nightly. Hopefully helps.

**Comment by JakeStanger** [comment]
Thanks. That's given more insight and it still looks like a bug with the library rather than a configuration issue. I can't see what would be throwing this from looking at the code though?

```
Connect-PnPOnline: /home/vsts/work/1/s/src/GenerateTemplate.ps1:13
Line |
  13 |      Connect-PnPOnline -Url $SiteUrl -ClientId $clientId -Tenant $tena …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Input string was not in a correct format. Failure to parse near offset
     | 67. Expected an ASCII digit.
```

**Comment by gautamdsheth** [comment]
@JakeStanger - hmm weird, I can't repro this. But I improved logging a bit and added some more logs, maybe that might help ? Would be also great if you can use Start/Stop-PnPTracelog , which should help in this with tomorrow's nightly.

**Comment by JakeStanger** [comment]
Turns out...I missed a digit when copying the Client ID GUID, so no wonder you couldn't. What you're seeing there is C# throw an error on a null byte. I'm not sure you could reasonably be expected to handle that :P

The good news is I have now been able to confirm it is all working and authenticating as expected, so  I'm happy at least to regard the feature stable and working.

Thanks for all your help and quick responses with this. I hope I didn't waste too much of your time having to look into it this afternoon.

**Comment by gautamdsheth** [comment]
@JakeStanger - no worries at all. Looks like there was some bug in the logging as well. Thanks for testing this.

Had a question related to implementation, in Azure DevOps we have the client Id and tenant values available via environment variables. Should we use this in our code instead of asking the user to specify the values so that we don't face the issue that you ran into ? If so, how do we handle GitHub where we dont have these env variables. Curious to know your thoughts on this and if we can improve this. 

@ryan-rosenburg - the release has been pushed a bit, we will do that after the summers here in Europe, sometime in August I believe. Having said that, the nightly builds are quite stable as such and there's rarely any major breaking change in them .

**Comment by JakeStanger** [comment]
I'd say yes, but still accept the args as optional. The majority of use cases are going to want to use the same values, but there may be cases where you want to use your own.

So something along the lines of:

```cs
var clientId = args.ClientId ?? Environment.GetEnvironmentVariable();
```

The only problem is you'd have to do a runtime check to ensure one of them is provided, in the case of GH or any future platforms.

**Comment by ryan-rosenburg** [comment]
@gautamdsheth - I appreciate the response but the timeline seems unreasonable. I work in a major Enterprise environment and we can only work from the Stable releases. We have been burned several times with the Nightly builds causing deployment issues. 
Microsoft's official documentation tells us to use the PnP community for deployment. And even having a full support contract with Microsoft, if the issue involves PnP we are told they don't support it and we need to come talk to you. 
We had to wait 9 months for PnP PowerShell Stable 2.12 to receive an update, even with the Nightly Builds going all the way to 2.99.*** 
This feature has been in progress for 2 years and provides huge security improvements to the environment, which aligns with Microsoft's Security First initiative.  I think it would be a benefit to your community if you push this into Stable release before the end of July.

**Comment by JakeStanger** [comment]
The workaround using Get-AzAccessToken and passing it to Connect-PnPOnline still works and can be used on stable. I'll be glad to see it in a stable release, but this flag is a convenience more than a necessity as far as I see it.

**Comment by LukasSchauffele** [comment]
Are there any updates on getting this released in stable?

**Comment by gautamdsheth** [comment]
We just released a new version today after more than a year with this feature.
You can use `-FederatedToken` parameter with Connect-PnPOnline which supports this.
Sorry and apologies for the delay and thanks for the patience , will close this feature request now !
