### ISSUE TITLE
[BUG] Remove-PnPFolder - File Not Found.

### ISSUE THREAD

**Issue by aaa7988** [pnp/powershell#3475]
### Reporting an Issue or Missing Feature
"Remove-PnPFolder -Folder $folderToDelete -Name $folderName -Force" results in File Not Found. 

I successfully perform the following:
# Get the folder to delete
$folderToDelete = Get-PnPFolder -Url $folderPath

#I can see the folder is stored correctly in the variable:
Name       Type   Items/Size Last Modified       
----       ----   ---------- -------------       
_AIP-Tests Folder         45 9/29/2023 9:57:11 PM

# Delete the folder
Remove-PnPFolder -Folder $folderToDelete -Name $folderName -Force
Remove-PnPFolder : File Not Found.
At line:2 char:1
+ Remove-PnPFolder -Folder $folderToDelete -Name $folderName -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Remove-PnPFolder], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.RemoveFolder

### Expected behavior 
I expect the folder to be deleted

### Actual behavior 
I receive the error "File Not Found"

### Steps to reproduce behavior
$userOneDriveURL = "https://company-my.sharepoint.com/personal/username"
$folderName = "_AIP-Tests"
$folderPath = "/personal/username/Documents/_AIP-Tests"

# Connect to the SPO Service
Connect-PnPOnline -Url $userOneDriveURL -UseWebLogin

# Get the folder to delete
$folderToDelete = Get-PnPFolder -Url $folderPath

# Delete the folder
Remove-PnPFolder -Folder $folderToDelete -Name $folderName -Force

# Disconnect from the SPO Service
Disconnect-PnPOnline

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows 11

**Comment by CallumCrowley** [comment]
@aaa7988 I think this is related to a problem (#3215) which was already reported and fixed in newer versions of PnP.PowerShell. Please upgrade to a newer version.

**Comment by morismm99** [comment]
I tried the delete a folder off an SPO site using Remove_PnPFolder and getting the same error ("Remove-PnPFolder: File Not Found." Running latest version of PnP on PowerShell 7. I tried with the "serverRelativeURL" property of the folder, and still does not work:

![image](https://github.com/pnp/powershell/assets/72099434/97bd20a6-a95b-42c3-966e-0f636e4ab2f9)

**Comment by morismm99** [comment]
Well....command is actually working correctly. For the -Folder parameter you need to pass the **parent** folder where the folder needing to be deleted resides in. This worked as expected:

Remove-PnPFolder -Name "DeleteMe" -Folder 'Shared Documents' -Force

:-)
