### ISSUE TITLE
[BUG] Connect-PnPOnline does not respect ErrorAction parameter

### ISSUE THREAD

**Issue by rgsteele** [pnp/powershell#3683]
### Reporting an Issue or Missing Feature
Issue (migrated from https://github.com/pnp/PnP-PowerShell/issues/2196)

### Expected behavior
`Connect-PnPOnline -ErrorAction Stop` stops script execution on error, e.g. when the URL is wrong.

### Actual behavior
The `-ErrorAction` parameter is being ignored, script execution continues.

### Steps to reproduce behavior
`Connect-PnPOnline` to a bogus tenant url

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by Studermarc** [comment]
There is the -ValidateConnection parameter which provides this feature.

It is described in the Documentation.

**Comment by imbrish** [comment]
I do not think `-ErrorAction` and `-ValidateConnection` work the same, for example when invalid credentials are given. I am using 1.1.12 in which `-ErrorAction` was supposedly added, but I do not think it works as expected.

```ps1
Get-Content "foo/bar" # -ErrorAction Stop
Connect-PnPOnline -Url "https://foo.bar" -Credentials "foobar" -ErrorAction Stop
Get-PnPListItem -List "foobar" -ErrorAction Stop
Get-PnPFile -Url "foo/bar" -AsFile -Path "." -Filename "bar" -ErrorAction Stop
Write-Host "finished"
```

This will show 4 errors and "finished" message. If I uncomment the `-ErrorAction` in the first line, the script will terminate after the first error.

**Comment by AndersRask** [comment]
ErrorAction was not added in any version, it is integral part of every cmdlet/advanced function. 

Some errors in PowerShell are terminating, some are not. By setting -ErrorAction Stop you ensure that the error will be terminating. Get-Content for example does not throw a terminating error if it cant find the file.

This is what often tricks people that wants error handling with try/catch. If the error is not terminating, it will not go into the catch and trigger your error handling!

For the case with Connect-PnPOnline, this was not treated as a "real" error, so you could not force the error into a catch to ensure your code flow. This was fixed when -ValidateConnection was added. Was it the right solution? I would have preferred a terminating error, and adding a new parameter also has issues for legacy code, but hey ho it works :)

https://devblogs.microsoft.com/scripting/understanding-non-terminating-errors-in-powershell/

**Comment by imbrish** [comment]
@AndersRask thanks for the explanation. I read the article you linked, and I guess I understand the difference between terminating and a non-terminating errors.

Compare the following script:

```ps1
Get-InstalledModule -Name "PnP.PowerShell"
Connect-PnPOnline -Url "https://foo.bar" -Credentials "foobar" -ErrorAction Stop
Write-Host "finished"
```

![image](https://github.com/pnp/powershell/assets/8572846/e0d53298-56be-441a-a472-4212d747c6e3)

And this one:

```ps1
$ErrorActionPreference = "Stop"
Get-InstalledModule -Name "PnP.PowerShell"
Connect-PnPOnline -Url "https://foo.bar" -Credentials "foobar"
Write-Host "finished"
```

![image](https://github.com/pnp/powershell/assets/8572846/43d998bc-2224-4e51-95fa-fd790ee45bcc)

Note that the "finished" line is missing. Shouldn't `-ErrorAction Stop` and `$ErrorActionPreference = "Stop"` be equivalent? Adding `-ValidateConnection` does not change anything.

**Comment by reshmee011** [comment]
@rgsteele : Closing this as issue #5171 addressed a similar scenario. Feel free to raise it again if the problem persists.

**Comment by rgsteele** [comment]
Hi @reshmee011, I have installed the latest nightly version (3.1.273) and the issue with the `Connect-PnPOnline` command is still occurring.

When running a test case analogous to the one that was provided in the bug that you linked using `Connect-PnPOnline` instead of `Disconnect-PnPOnline`, I get the following:

```
try {Connect-PnPOnline -URL https://bogus -ErrorAction SilentlyContinue } catch { Write-Host "Got here" }
WARNING:
 Please specify a valid client id for an Entra ID App Registration.


Got here
```

**Comment by reshmee011** [comment]
HI @rgsteele ,just a heads-up starting from version 3.10 of the PnP PowerShell module, Connect-PnPOnline requires you to register your own Entra ID app. This is a change from version 2. You can find the details here:https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html

**Comment by rgsteele** [comment]
Thanks @reshmee011 . I am aware of the requirement to register the Entra ID app but I didn't include the parameter for that in the command because it wasn't relevant to the example.

Can you please confirm that this issue will not be closed, given that the issue is not resolved? Thanks!

**Comment by reshmee011** [comment]
Got it, https://github.com/pnp/powershell/issues/5171 covers the same scenario for Disconnect-PnPOnline. This request, however, is for Connect-PnPOnline. I’ll look into it.

**Comment by reshmee011** [comment]
I’ve looked through the code, and it runs across several layers with quite a lot happening. I’m honestly not sure what the best way to approach it is.
