### ISSUE TITLE
[BUG] Get-PnPGroupPermissions: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by adzero** [pnp/powershell#389]
### Reporting an Issue
Please confirm what it is that your reporting

### Expected behavior 
Expecting to get permissions for a group identified by its title.

### Actual behavior 
Command raises a NullReferenceException when specifying a group name (existing or not). 
Notice that no exception occurs when passing a group object or its Id... and of course no results either. 

### Steps to reproduce behavior
Connect-PnPOnline -Url $url -Credentials $credentials
$group = Get-PnPGroup -AssociatedOwnerGroup
Get-PnPGroupPermissions -Identity $group.Title

### What is the version of the Cmdlet module you are running?
PnP.PowerShell version 1.3.19-nightly (same with 1.2.6-nightly)

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Regarding seeing no results: there was a change in the underlying API that was not reflected in the cmdlet. We just merged a fix and it will be available in the 1.3.23 nightly release.

Regarding the fact that if you specify the title of the group you receive an error: is there something specific in the group title that might cause this? Like special characters or diacritic characters?

**Comment by adzero** [comment]
@erwinvanhunen , the group names are default team site group names on the site I used to reproduce the problem, but in french. 
For example, the owner group is : _Propriétaires de Demande n°1_

**Comment by erwinvanhunen** [comment]
Then I'm almost sure the French characters are causing the issue. I'll debug this to find out what's causing this.

**Comment by adzero** [comment]
@erwinvanhunen , 

I checked with a member group without any french character and it's the same : 

`Get-PnPGroupPermissions -Identity "Demande n°1 - Membres"`

**Comment by erwinvanhunen** [comment]
There is however still a special character in there: °

My assumption is that we do not encode certain values in the Core SDK behind the scenes correctly.

**Comment by erwinvanhunen** [comment]
I just checked with the latest build on my machine and with the change I merged earlier groups will special characters will return the data correctly. If no permissions where set in the currently released build you would have received an exception. I changed that behavior to return nothing now. Please check tomorrow the 1.3.23-nightly build.

**Comment by adzero** [comment]
Ok, I'll check. 

Thank you.

**Comment by adzero** [comment]
Hello @erwinvanhunen , 

I just updated to 1.3.23-nightly and did the tests again :

`Get-PnPGroupPermissions -Identity "Membres"` is returning a result now. 
`Get-PnPGroupPermissions -Identity "Propriétaires"` still throws a null reference exception
`Get-PnPGroupPermissions -Identity "Demande n°1 - Membres"` still throws a null reference exception

**Comment by erwinvanhunen** [comment]
the moment you receive the exception could you immediately after that run

```
Get-PnPException
```

and paste the results here? Thanks!

**Comment by erwinvanhunen** [comment]
If you enter

```powershell
Get-PnPGroup
```

E.g. without parameters, does the "Propriétaires" and "Demande n°1 - Membres" groups show?

I created a group through the UI, called it "Propriétaires de Demande n°1", I assigned some rights but I'm having no issues:

![image](https://user-images.githubusercontent.com/7666381/110631441-cf746c80-81a6-11eb-8017-599d359675e7.png)

**Comment by adzero** [comment]
![image](https://user-images.githubusercontent.com/7522988/110637381-a3101e80-81ad-11eb-911e-1c27b84453e2.png)

![image](https://user-images.githubusercontent.com/7522988/110636979-38f77980-81ad-11eb-93c0-132b162cd92e.png)

**Comment by rom-1** [comment]
can confirm the very same problem with get-pnpgrouppermissions and set-PnPGrouppermissions with german umlaut characters. As long as our groups do not contain the letters: ä, ü, ö, ß - there is no issue. But one of these letters in the group name throws the excpetion.

![2021-03-18_14h39_35](https://user-images.githubusercontent.com/37835829/111635464-c95e3b80-87f7-11eb-91a4-2bc880084cda.png)

**Comment by rom-1** [comment]
Why is this issue being closed? Problem still exists with PnP.Powershell 1.5.0 - should I reopen a new issue?

**Comment by veronicageek** [comment]
Might potentially also be linked with issue #574

**Comment by erwinvanhunen** [comment]
After more debugging we potentially found the issue in this case. It seems to be related to the way the Core SDK handles URLs with diacritic characters. We will forward this issue to that repo so we can take care of if there.
