### ISSUE TITLE
[BUG] Issue when applying tenant template using AAD app-only access

### ISSUE THREAD

**Issue by joelfmrodrigues** [pnp/powershell#43]
### Reporting an Issue or Missing Feature

I believe this may be an issue in PnP PowerShell and not the provisioning engine, but happy to move it if wrong location.

Invoke-PnPTenantTemplate fails the first time when provisioning a template with a related SharePoint site and Teams team.
This only happens when connecting using Azure AD app-only access. If connecting using a user account (username + password) all works as expected.

![image](https://user-images.githubusercontent.com/19577724/101343066-5ac62500-387b-11eb-936b-bf90eceb1f26.png)

### Expected behavior 

Be able to connect using ADD app-only and apply a tenant template for SharePoint and Teams.

### Actual behavior 

The first time the command is executed it will fail as per the image above. If we execute the command a second time, it works. 

### Steps to reproduce behavior
Register an Azure AD app as per the following documentation: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread

Create an XML template which provisions a SharePoint Site and Teams team: example: https://www.collabmagazine.com/provisioning-teams-in-microsoft-teams-using-the-pnp-provisioning-engine/

Connect to SharePoint using AAD app registration (Client ID + Tenant + Thumbprint)

Execute Invoke-PnPTenantTemplate --> this should fail the first time
Execute Invoke-PnPTenantTemplate a second time --> this should now work

### What is the version of the Cmdlet module you are running?
0.2.22

**Comment by joelfmrodrigues** [comment]
Some logging

[2020-12-07T15:24:54.933Z] ERROR: Exception while invoking endpoint https://graph.microsoft.com/v1.0/teams/ac20edf6-713f-4e05-850e-f0864d3541b5/channels.
[2020-12-07T15:24:54.935Z] 
[2020-12-07T15:24:54.935Z] Exception             : 
[2020-12-07T15:24:54.943Z]     Type           : System.ApplicationException
[2020-12-07T15:24:54.944Z]     TargetSite     : 
[2020-12-07T15:24:54.945Z]         Name          : ApplyTenantTemplate
[2020-12-07T15:24:54.945Z]         DeclaringType : PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion, PnP.Framework, Version=0.1.70.0, Culture=neutral, PublicKeyToken=null
[2020-12-07T15:24:54.946Z]         MemberType    : Method
[2020-12-07T15:24:54.947Z]         Module        : PnP.Framework.dll
[2020-12-07T15:24:54.948Z]     StackTrace     : 
[2020-12-07T15:24:54.948Z]    at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ApplyConfiguration configuration)
[2020-12-07T15:24:54.949Z]    at Microsoft.SharePoint.Client.TenantExtensions.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy tenantTemplate, String sequenceId, ApplyConfiguration configuration)
[2020-12-07T15:24:54.950Z]    at PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate.ExecuteCmdlet() in D:\a\powershell\powershell\src\Commands\Provisioning\Tenant\InvokeTenantTemplate.cs:line 349
[2020-12-07T15:24:54.950Z]    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 56
[2020-12-07T15:24:54.951Z]     Message        : Exception while invoking endpoint https://graph.microsoft.com/v1.0/teams/ac20edf6-713f-4e05-850e-f0864d3541b5/channels.
[2020-12-07T15:24:54.952Z]     Data           : System.Collections.ListDictionaryInternal
[2020-12-07T15:24:54.966Z]     InnerException : 
[2020-12-07T15:24:54.967Z]         Type    : System.Exception
[2020-12-07T15:24:54.967Z]         Message : {
[2020-12-07T15:24:54.968Z]                   "error": {
[2020-12-07T15:24:54.978Z]                   "code": "NotFound",
[2020-12-07T15:24:54.979Z]                   "message": "No Team found with Group id: ac20edf6-713f-4e05-850e-f0864d3541b5",
[2020-12-07T15:24:54.979Z]                   "innerError": {
[2020-12-07T15:24:54.981Z]                   "date": "2020-12-07T15:24:55",
[2020-12-07T15:24:54.982Z]                   "request-id": "84ab2d04-5f98-42e3-a86c-c51aa4adcc73",
[2020-12-07T15:24:54.983Z]                   "client-request-id": "84ab2d04-5f98-42e3-a86c-c51aa4adcc73"
[2020-12-07T15:24:54.984Z]                   }
[2020-12-07T15:24:54.985Z]                   }
[2020-12-07T15:24:54.995Z]                   }
[2020-12-07T15:24:54.996Z]         HResult : -2146233088
[2020-12-07T15:24:54.996Z]     Source         : PnP.Framework
[2020-12-07T15:24:54.997Z]     HResult        : -2146232832
[2020-12-07T15:24:54.998Z] CategoryInfo          : WriteError: (:) [Invoke-PnPTenantTemplate], ApplicationException
[2020-12-07T15:24:54.999Z] FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate
[2020-12-07T15:24:55.000Z] ErrorDetails          : Exception while invoking endpoint https://graph.microsoft.com/v1.0/teams/ac20edf6-713f-4e05-850e-f0864d3541b5/channels.
[2020-12-07T15:24:55.001Z] InvocationInfo        : 
[2020-12-07T15:24:55.002Z]     MyCommand        : Invoke-PnPPnPTenantTemplate
[2020-12-07T15:24:55.013Z]     ScriptLineNumber : 37
[2020-12-07T15:24:55.014Z]     OffsetInLine     : 1
[2020-12-07T15:24:55.014Z]     HistoryId        : 23
[2020-12-07T15:24:55.015Z]     ScriptName       : C:\Dev\XXXXXXXXXXXX\Solution\Provisioning\run.ps1
[2020-12-07T15:24:55.016Z]     Line             : Invoke-PnPTenantTemplate -Path ../Test/TestTemplate1.xml -Parameters $templateParameters
[2020-12-07T15:24:55.017Z]     PositionMessage  : At C:\Dev\XXXXXXXXXXXX\Solution\Provisioning\run.ps1:37 char:1
[2020-12-07T15:24:55.018Z]                        + Invoke-PnPTenantTemplate -Path ../Test/TestTemplate1.xml -Parameters  .
[2020-12-07T15:24:55.027Z]                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2020-12-07T15:24:55.028Z]     PSScriptRoot     : C:\Dev\XXXXXXXXXXXX\Solution\Provisioning
[2020-12-07T15:24:55.029Z]     PSCommandPath    : C:\Dev\XXXXXXXXXXXX\Solution\Provisioning\run.ps1
[2020-12-07T15:24:55.030Z]     InvocationName   : Invoke-PnPTenantTemplate
[2020-12-07T15:24:55.031Z]     CommandOrigin    : Internal
[2020-12-07T15:24:55.031Z] ScriptStackTrace      : at <ScriptBlock>, C:\Dev\XXXXXXXXXXXX\Solution\Provisioning\run.ps1: line 37
[2020-12-07T15:24:55.032Z] PipelineIterationInfo : 
[2020-12-07T15:24:55.033Z] 
[2020-12-07T15:24:55.034Z] 
[2020-12-07T15:24:55.034Z] 
[2020-12-07T15:24:55.035Z] 
[2020-12-07T15:24:55.045Z] 
[2020-12-07T15:24:55.046Z] Result: ERROR: Exception while invoking endpoint https://graph.microsoft.com/v1.0/teams/ac20edf6-713f-4e05-850e-f0864d3541b5/channels.
[2020-12-07T15:24:55.048Z] 
[2020-12-07T15:24:55.048Z] Exception             : 
[2020-12-07T15:24:55.049Z]     Type           : System.ApplicationException
[2020-12-07T15:24:55.050Z]     TargetSite     : 
[2020-12-07T15:24:55.051Z]         Name          : ApplyTenantTemplate
[2020-12-07T15:24:55.051Z]         DeclaringType : PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion, PnP.Framework, Version=0.1.70.0, Culture=neutral, PublicKeyToken=null
[2020-12-07T15:24:55.059Z]         MemberType    : Method
[2020-12-07T15:24:55.059Z]         Module        : PnP.Framework.dll
[2020-12-07T15:24:55.060Z]     StackTrace     : 
[2020-12-07T15:24:55.061Z]    at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ApplyConfiguration configuration)
[2020-12-07T15:24:55.061Z]    at Microsoft.SharePoint.Client.TenantExtensions.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy tenantTemplate, String sequenceId, ApplyConfiguration configuration)
[2020-12-07T15:24:55.062Z]    at PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate.ExecuteCmdlet() in D:\a\powershell\powershell\src\Commands\Provisioning\Tenant\InvokeTenantTemplate.cs:line 349
[2020-12-07T15:24:55.062Z]    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 56
[2020-12-07T15:24:55.063Z]     Message        : Exception while invoking endpoint https://graph.microsoft.com/v1.0/teams/ac20edf6-713f-4e05-850e-f0864d3541b5/channels.
[2020-12-07T15:24:55.063Z]     Data           : System.Collections.ListDictionaryInternal
[2020-12-07T15:24:55.064Z]     InnerException : 
[2020-12-07T15:24:55.065Z]         Type    : System.Exception
[2020-12-07T15:24:55.065Z]         Message : {
[2020-12-07T15:24:55.066Z]                   "error": {
[2020-12-07T15:24:55.066Z]                   "code": "NotFound",
[2020-12-07T15:24:55.067Z]                   "message": "No Team found with Group id: ac20edf6-713f-4e05-850e-f0864d3541b5",
[2020-12-07T15:24:55.067Z]                   "innerError": {
[2020-12-07T15:24:55.068Z]                   "date": "2020-12-07T15:24:55",
[2020-12-07T15:24:55.077Z]                   "request-id": "84ab2d04-5f98-42e3-a86c-c51aa4adcc73",
[2020-12-07T15:24:55.078Z]                   "client-request-id": "84ab2d04-5f98-42e3-a86c-c51aa4adcc73"
[2020-12-07T15:24:55.079Z]                   }
[2020-12-07T15:24:55.079Z]                   }
[2020-12-07T15:24:55.080Z]                   }
[2020-12-07T15:24:55.081Z]         HResult : -2146233088
[2020-12-07T15:24:55.081Z]     Source         : PnP.Framework
[2020-12-07T15:24:55.081Z]     HResult        : -2146232832
[2020-12-07T15:24:55.082Z] CategoryInfo          : WriteError: (:) [Invoke-PnPTenantTemplate], ApplicationException
[2020-12-07T15:24:55.083Z] FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate
[2020-12-07T15:24:55.083Z] ErrorDetails          : Exception while invoking endpoint https://graph.microsoft.com/v1.0/teams/ac20edf6-713f-4e05-850e-f0864d3541b5/channels.
[2020-12-07T15:24:55.084Z] InvocationInfo        : 
[2020-12-07T15:24:55.084Z]     MyCommand        : Invoke-PnPPnPTenantTemplate
[2020-12-07T15:24:55.085Z]     ScriptLineNumber : 37
[2020-12-07T15:24:55.092Z]     OffsetInLine     : 1
[2020-12-07T15:24:55.093Z]     HistoryId        : 23
[2020-12-07T15:24:55.093Z]     ScriptName       : C:\Dev\\XXXXXXXXXXXX\Solution\Provisioning\run.ps1
[2020-12-07T15:24:55.094Z]     Line             : Invoke-PnPTenantTemplate -Path ../Test/TestTemplate1.xml -Parameters $templateParameters
[2020-12-07T15:24:55.095Z]     PositionMessage  : At C:\Dev\XXXXXXXXXXXX\Solution\Provisioning\run.ps1:37 char:1
[2020-12-07T15:24:55.095Z]                        + Invoke-PnPTenantTemplate -Path ../Test/TestTemplate1.xml -Parameters  .
[2020-12-07T15:24:55.096Z]                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2020-12-07T15:24:55.096Z]     PSScriptRoot     : C:\Dev\XXXXXXXXXXXX\Solution\Provisioning
[2020-12-07T15:24:55.097Z]     PSCommandPath    : C:\Dev\XXXXXXXXXXXX\Solution\Provisioning\run.ps1
[2020-12-07T15:24:55.098Z]     InvocationName   : Invoke-PnPTenantTemplate
[2020-12-07T15:24:55.098Z]     CommandOrigin    : Internal
[2020-12-07T15:24:55.099Z] ScriptStackTrace      : at <ScriptBlock>, C:\Dev\XXXXXXXXXXXX\Solution\Provisioning\run.ps1: line 37
[2020-12-07T15:24:55.099Z] PipelineIterationInfo :
[2020-12-07T15:24:55.100Z]
[2020-12-07T15:24:55.100Z]
[2020-12-07T15:24:55.101Z]
[2020-12-07T15:24:55.101Z]
[2020-12-07T15:24:55.102Z]
Exception: Exception while invoking endpoint https://graph.microsoft.com/v1.0/teams/ac20edf6-713f-4e05-850e-f0864d3541b5/channels.
Stack:    at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ApplyConfiguration configuration)
[2020-12-07T15:24:55.111Z]    at Microsoft.SharePoint.Client.TenantExtensions.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy tenantTemplate, String sequenceId, ApplyConfiguration configuration)
[2020-12-07T15:24:55.112Z]    at PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate.ExecuteCmdlet() in D:\a\powershell\powershell\src\Commands\Provisioning\Tenant\InvokeTenantTemplate.cs:line 349
[2020-12-07T15:24:55.113Z]    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 56.

**Comment by erwinvanhunen** [comment]
We found a bug in the teams provisioning engine if you use AAD app-only token and you want to provision a team -AND- you did not specify the owner of the team. That combination is important in that scenario we will first great the group, but without an owner. After the group has been created we teamify the group. However, because there is no owner, that process will fail. We fixed it now in such a way that:

1. If a template contains an owner, we will we as normal create the group with that owner if needed
1. If you use app-only auth and your template does not contain an owner, we will fail with an exception, there is no way for us to create the group with an owner which is needed to teamify it. However, if the group is already there, we will use that of course.
1. If you use  delegate auth and your template does nto contain an owner, we will use the username we extract from the delegate access token

This fix was merged yesterday and made available in the currently available nightly build of both the PnP.Framework and PnP PowerShell (0.3.9-nightly)

Between 0.2.22 and 0.3.9 we have done considerable changes to the underlying auth and access token handling of the PnP Framework, so please upgrade to the latest nightly and try again.

**Comment by joelfmrodrigues** [comment]
Thanks so much @erwinvanhunen. I will test and provide an update over the next days

**Comment by joelfmrodrigues** [comment]
@erwinvanhunen just getting back to test this (apologies for the delay)

I updated to the latest nightly build (today) and still getting the same error.
My template is specifying an owner for the team:

![image](https://user-images.githubusercontent.com/19577724/103536331-3a918200-4e8a-11eb-93fb-ac959fbf71d9.png)

**Comment by erwinvanhunen** [comment]
I just tested it here again, and I have no issues... In your template: the OwnerUPN is actually set? Can you try with a hardcoded value?

**Comment by joelfmrodrigues** [comment]
Tried with hardcoded value and still failed, only works on the second retry. Without looking at the code (sorry if this makes no sense) could it be that the request is being executed before the team was fully created? 


[2021-01-06T14:35:00.907Z] Executed 'Functions.Provisioning' (Failed, Id=4bc120bf-fca4-447f-9e9a-45161d042746, Duration=77695ms)
[2021-01-06T14:35:00.914Z] System.Private.CoreLib: Exception while executing function: Functions.Provisioning. System.Private.CoreLib: Result: Failure
Exception: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception while invoking endpoint https://graph.microsoft.com/v1.0/teams/637f5a3f-f488-45d9-91ea-9ca9cea4b726/channels.
Stack:    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
[2021-01-06T14:35:00.915Z]    at System.Management.Automation.Runspaces.Pipeline.Invoke()
[2021-01-06T14:35:00.916Z]    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
[2021-01-06T14:35:00.919Z]    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
[2021-01-06T14:35:00.919Z]    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
[2021-01-06T14:35:00.920Z]    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
[2021-01-06T14:35:00.955Z]    at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
[2021-01-06T14:35:00.956Z]    at System.Management.Automation.PowerShell.Invoke[T]()
[2021-01-06T14:35:00.957Z]    at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellExtensions.InvokeAndClearCommands[T](PowerShell pwsh) in D:\a\1\s\src\PowerShell\PowerShellExtensions.cs:line 45
[2021-01-06T14:35:00.957Z]    at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeNonOrchestrationFunction(DurableController durableController, IDictionary outputBindings) in D:\a\1\s\src\PowerShell\PowerShellManager.cs:line 283
[2021-01-06T14:35:00.958Z]    at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeFunction(AzFunctionInfo functionInfo, Hashtable triggerMetadata, TraceContext traceContext, IList`1 inputData, FunctionInvocationPerformanceStopwatch stopwatch) in D:\a\1\s\src\PowerShell\PowerShellManager.cs:line 226
[2021-01-06T14:35:00.959Z]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.InvokeFunction(AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch, InvocationRequest invocationRequest) in D:\a\1\s\src\RequestProcessor.cs:line 333
[2021-01-06T14:35:00.959Z]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequestImpl(StreamingMessage request, AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch) in D:\a\1\s\src\RequestProcessor.cs:line 306.

**Comment by joelfmrodrigues** [comment]
Just a note that I have tested using the 0.3.26-nightly build

**Comment by gautamdsheth** [comment]
@joelfmrodrigues - in the app-only scenario, can you remove these attributes from the template and check ? 

`Teamify="true"
HideTeamify="true"`

**Comment by joelfmrodrigues** [comment]
@gautamdsheth same error. Also seems to have the same end result after the request is executed a second time as it then works. Are these options not required/compatible with app-only?

I also just noticed that the group does not have a team when I get the error, but it seems to appear a few seconds after the error
![image](https://user-images.githubusercontent.com/19577724/103887356-d1ed1400-50da-11eb-8bb2-f5f1cf9c3367.png)

**Comment by joelfmrodrigues** [comment]
@gautamdsheth let me correct my last reply. The team is not available after a few seconds, but after the template is applied a second time. I'm using a queue + Function and this is so fast to retry that I didn't notice it before.

**Comment by gautamdsheth** [comment]
2 things 

1) Can you try with latest update tomorrow, have changed team creation a bit so it would help ? 
2) If you creating a message `<pnp:Messages>`, can you remove that in the template in app-only scenario I think ?

Thanks :)

**Comment by joelfmrodrigues** [comment]
@gautamdsheth sorry the late reply

Just tried with today's build (0.3.35), but same error:
"No Team found with Group id: 60634915-43c0-43e3-9f20-819931578e30"

The group exists and the ID is correct, but it's not associated with a team

![image](https://user-images.githubusercontent.com/19577724/104588690-ac26b880-5660-11eb-9727-9409a8454730.png)

Regarding `<pnp:Messages>`, I'm not using them.

Error details

EXCEPTION: Exception while invoking endpoint https://graph.microsoft.com/v1.0/teams/60634915-43c0-43e3-9f20-819931578e30/channels.
[2021-01-14T11:59:04.610Z] 
[2021-01-14T11:59:04.612Z] Exception             : 
[2021-01-14T11:59:04.612Z]     Type           : System.ApplicationException
[2021-01-14T11:59:04.613Z]     TargetSite     : 
[2021-01-14T11:59:04.613Z]         Name          : ApplyTenantTemplate
[2021-01-14T11:59:04.614Z]         DeclaringType : PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion, PnP.Framework, Version=0.1.114.0, Culture=neutral, PublicKeyToken=null
[2021-01-14T11:59:04.614Z]         MemberType    : Method
[2021-01-14T11:59:04.615Z]         Module        : PnP.Framework.dll
[2021-01-14T11:59:04.616Z]     StackTrace     : 
[2021-01-14T11:59:04.616Z]    at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ApplyConfiguration configuration)
[2021-01-14T11:59:04.617Z]    at Microsoft.SharePoint.Client.TenantExtensions.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy tenantTemplate, String sequenceId, ApplyConfiguration configuration)
[2021-01-14T11:59:04.618Z]    at PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate.ExecuteCmdlet() in D:\a\powershell\powershell\src\Commands\Provisioning\Tenant\InvokeTenantTemplate.cs:line 375
[2021-01-14T11:59:04.618Z]    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 59
[2021-01-14T11:59:04.619Z]     Message        : Exception while invoking endpoint https://graph.microsoft.com/v1.0/teams/60634915-43c0-43e3-9f20-819931578e30/channels.
[2021-01-14T11:59:04.619Z]     Data           : System.Collections.ListDictionaryInternal
[2021-01-14T11:59:04.621Z]     InnerException : 
[2021-01-14T11:59:04.621Z]         Type    : System.Exception
[2021-01-14T11:59:04.622Z]         Message : {
[2021-01-14T11:59:04.623Z]                   "error": {
[2021-01-14T11:59:04.624Z]                   "code": "NotFound",
[2021-01-14T11:59:04.624Z]                   "message": "No Team found with Group id: 60634915-43c0-43e3-9f20-819931578e30",
[2021-01-14T11:59:04.625Z]                   "innerError": {
[2021-01-14T11:59:04.626Z]                   "date": "2021-01-14T11:59:04",

**Comment by erwinvanhunen** [comment]
Hi @joelfmrodrigues : we found a flaw in our teamify code in the engine, which we fixed. Could you please check with the release of 0.3.36-nightly of PnP PowerShell which will be out tomorrow.

**Comment by joelfmrodrigues** [comment]
Hi @erwinvanhunen 

I am not getting a different error, but it seems to happen at the same stage of the process (based on the logs)

AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope Group.ReadWrite.All is not valid.

While before I could complete provisioning applying the same template again as there were no errors on the second attempt, this error is persistent.


[2021-01-15T14:40:13.443Z]     CorrelationId : 4f8d03d9-0850-4181-9486-21b55fb4e9c0
[2021-01-15T14:40:13.444Z]     ErrorCode     : invalid_scope
[2021-01-15T14:40:13.445Z]     TargetSite    : 
[2021-01-15T14:40:13.445Z]         Name          : ApplyTenantTemplate
[2021-01-15T14:40:13.447Z]         DeclaringType : PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion, PnP.Framework, Version=0.1.115.0, Culture=neutral, PublicKeyToken=null
[2021-01-15T14:40:13.447Z]         MemberType    : Method
[2021-01-15T14:40:13.448Z]         Module        : PnP.Framework.dll
[2021-01-15T14:40:13.448Z]     StackTrace    : 
[2021-01-15T14:40:13.449Z]    at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ApplyConfiguration configuration)
[2021-01-15T14:40:13.449Z]    at Microsoft.SharePoint.Client.TenantExtensions.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy tenantTemplate, String sequenceId, ApplyConfiguration configuration)
[2021-01-15T14:40:13.450Z]    at PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate.ExecuteCmdlet() in D:\a\powershell\powershell\src\Commands\Provisioning\Tenant\InvokeTenantTemplate.cs:line 376
[2021-01-15T14:40:13.450Z]    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 59
[2021-01-15T14:40:13.451Z]     Message       : AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope Group.ReadWrite.All is not valid.
[2021-01-15T14:40:13.461Z]                     Trace ID: e6dab88b-7a7c-434e-8490-4ee526aa1c00
[2021-01-15T14:40:13.461Z]                     Correlation ID: 4f8d03d9-0850-4181-9486-21b55fb4e9c0
[2021-01-15T14:40:13.462Z]                     Timestamp: 2021-01-15 14:40:13Z
[2021-01-15T14:40:13.463Z]     Data          : System.Collections.ListDictionaryInternal
[2021-01-15T14:40:13.464Z]     Source        : PnP.Framework
[2021-01-15T14:40:13.464Z]     HResult       : -2146233088
[2021-01-15T14:40:13.465Z] CategoryInfo          : WriteError: (:) [Invoke-PnPTenantTemplate], MsalServiceException
[2021-01-15T14:40:13.465Z] FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate
[2021-01-15T14:40:13.466Z] ErrorDetails          : AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope Group.ReadWrite.All is not valid.
[2021-01-15T14:40:13.466Z]                         Trace ID: e6dab88b-7a7c-434e-8490-4ee526aa1c00
[2021-01-15T14:40:13.467Z]                         Correlation ID: 4f8d03d9-0850-4181-9486-21b55fb4e9c0
[2021-01-15T14:40:13.467Z]                         Timestamp: 2021-01-15 14:40:13Z

**Comment by erwinvanhunen** [comment]
Yes, we missed a part. We're getting closer though :-) We know why that is happening .As you are using clientid/certificate auth, e.g. app only, we need to request the default scope instead of a specific scope. I have a commit waiting here that will go out today.

**Comment by joelfmrodrigues** [comment]
@erwinvanhunen Just tested this and getting a different error - I believe at the same stage

Error message: 
AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope graph.microsoft.com/.default is not valid.

Full error details:

2021-01-20T15:23:36.680 [Error] EXCEPTION: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope graph.microsoft.com/.default is not valid.Trace ID: 06c50383-b3f2-4091-a883-ac3c526fb200Correlation ID: 2f54239b-9beb-4615-9897-39b792d000e1Timestamp: 2021-01-20 15:23:35ZException             :Type          : Microsoft.Identity.Client.MsalServiceExceptionStatusCode    : 400ResponseBody  : {"error":"invalid_scope","error_description":"AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope graph.microsoft.com/.default is not valid.\r\nTrace ID: 06c50383-b3f2-4091-a883-ac3c526fb200\r\nCorrelation ID: 2f54239b-9beb-4615-9897-39b792d000e1\r\nTimestamp: 2021-01-20 15:23:35Z","error_codes":[70011],"timestamp":"2021-01-20 15:23:35Z","trace_id":"06c50383-b3f2-4091-a883-ac3c526fb200","correlation_id":"2f54239b-9beb-4615-9897-39b792d000e1"}Headers       :Key   : Cache-ControlValue :Length : 18Key   : PragmaValue :Length : 8Key   : Strict-Transport-SecurityValue :Length : 35Key   : X-Content-Type-OptionsValue :Length : 7Key   : P3PValue :Length : 34Key   : client-request-idValue :Length : 36Key   : x-ms-request-idValue :Length : 36Key   : x-ms-ests-serverValue :Length : 30Key   : x-ms-clitelemValue :Length : 11Key   : Set-CookieValue :Length : 171Length : 49Length : 64Key   : DateValue :Length : 29CorrelationId : 2f54239b-9beb-4615-9897-39b792d000e1ErrorCode     : invalid_scopeTargetSite    :Name          : ApplyTenantTemplateDeclaringType : PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion, PnP.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=nullMemberType    : MethodModule        : PnP.Framework.dllStackTrace    :at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ApplyConfiguration configuration) in C:\repos\pnpframework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 212at Microsoft.SharePoint.Client.TenantExtensions.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy tenantTemplate, String sequenceId, ApplyConfiguration configuration) in C:\repos\pnpframework\src\lib\PnP.Framework\Extensions\TenantExtensions.cs:line 43at PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate.ExecuteCmdlet() in C:\repos\powershell\src\Commands\Provisioning\Tenant\InvokeTenantTemplate.cs:line 316at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in C:\repos\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 59Message       : AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope graph.microsoft.com/.default is not valid.Trace ID: 06c50383-b3f2-4091-a883-ac3c526fb200Correlation ID: 2f54239b-9beb-4615-9897-39b792d000e1Timestamp: 2021-01-20 15:23:35ZData          : System.Collections.ListDictionaryInternalSource        : PnP.FrameworkHResult       : -2146233088CategoryInfo          : WriteError: (:) [Invoke-PnPTenantTemplate], MsalServiceExceptionFullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplateErrorDetails          : AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope graph.microsoft.com/.default is not valid.Trace ID: 06c50383-b3f2-4091-a883-ac3c526fb200Correlation ID: 2f54239b-9beb-4615-9897-39b792d000e1Timestamp: 2021-01-20 15:23:35ZInvocationInfo        :MyCommand        : Invoke-PnPTenantTemplateScriptLineNumber : 92OffsetInLine     : 1HistoryId        : 1ScriptName       : C:\home\site\wwwroot\Provisioning\run.ps1Line             : Invoke-PnPTenantTemplate -Path "$TEMPLATESPATH/$templateFile" -Parameters $templateParametersPositionMessage  : At C:\home\site\wwwroot\Provisioning\run.ps1:92 char:1+ Invoke-PnPTenantTemplate -Path "$TEMPLATESPATH/$templateFile" -Parame …+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\ProvisioningPSCommandPath    : C:\home\site\wwwroot\Provisioning\run.ps1InvocationName   : Invoke-PnPTenantTemplateCommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\Provisioning\run.ps1: line 92PipelineIterationInfo :
2021-01-20T15:23:36.827 [Error] Executed 'Functions.Provisioning' (Failed, Id=5a059a72-e989-4413-93ae-d4a4c0ee5ba2, Duration=71953ms)Result: FailureException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope graph.microsoft.com/.default is not valid.Trace ID: 06c50383-b3f2-4091-a883-ac3c526fb200Correlation ID: 2f54239b-9beb-4615-9897-39b792d000e1Timestamp: 2021-01-20 15:23:35ZStack:    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)at System.Management.Automation.Runspaces.Pipeline.Invoke()at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)at System.Management.Automation.PowerShell.Invoke[T]()at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellExtensions.InvokeAndClearCommands[T](PowerShell pwsh) in D:\a\1\s\src\PowerShell\PowerShellExtensions.cs:line 45at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeNonOrchestrationFunction(DurableController durableController, IDictionary outputBindings) in D:\a\1\s\src\PowerShell\PowerShellManager.cs:line 283at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeFunction(AzFunctionInfo functionInfo, Hashtable triggerMetadata, TraceContext traceContext, IList`1 inputData, FunctionInvocationPerformanceStopwatch stopwatch) in D:\a\1\s\src\PowerShell\PowerShellManager.cs:line 226at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.InvokeFunction(AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch, InvocationRequest invocationRequest) in D:\a\1\s\src\RequestProcessor.cs:line 333at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequestImpl(StreamingMessage request, AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch) in D:\a\1\s\src\RequestProcessor.cs:line 306

**Comment by erwinvanhunen** [comment]
Found the issue and fixed it. Please try the 1.2.5-nightly release when available (it will be out tomorrow, 2012-01-26)

**Comment by joelfmrodrigues** [comment]
Tested with 1.2.6-nightly, but getting a different error (I think at the same step)


[2021-01-27T14:17:19.330Z] EXCEPTION: Team with id 5034c8af-f5e3-4187-ada4-972ffca12d6d not created within timeout.
[2021-01-27T14:17:19.332Z] 
[2021-01-27T14:17:19.333Z] Exception             : 
[2021-01-27T14:17:19.333Z]     Type       : System.Exception
[2021-01-27T14:17:19.335Z]     Message    : Team with id 5034c8af-f5e3-4187-ada4-972ffca12d6d not created within timeout.
[2021-01-27T14:17:19.336Z]     TargetSite : 
[2021-01-27T14:17:19.337Z]         Name          : ApplyTenantTemplate
[2021-01-27T14:17:19.338Z]         DeclaringType : PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion, PnP.Framework, Version=1.1.6.0, Culture=neutral, PublicKeyToken=null
[2021-01-27T14:17:19.338Z]         MemberType    : Method
[2021-01-27T14:17:19.339Z]         Module        : PnP.Framework.dll
[2021-01-27T14:17:19.340Z]     StackTrace : 
[2021-01-27T14:17:19.341Z]    at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ApplyConfiguration configuration)
[2021-01-27T14:17:19.342Z]    at Microsoft.SharePoint.Client.TenantExtensions.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy tenantTemplate, String sequenceId, ApplyConfiguration configuration)
[2021-01-27T14:17:19.343Z]    at PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate.ExecuteCmdlet() in D:\a\powershell\powershell\src\Commands\Provisioning\Tenant\InvokeTenantTemplate.cs:line 316
[2021-01-27T14:17:19.344Z]    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 59
[2021-01-27T14:17:19.344Z]     Data       : System.Collections.ListDictionaryInternal
[2021-01-27T14:17:19.365Z]     Source     : PnP.Framework
[2021-01-27T14:17:19.366Z]     HResult    : -2146233088

**Comment by joelfmrodrigues** [comment]
Just a note for someone who may be facing the same issue: I have been able to avoid the error by creating the group and team before applying the template
``` PowerShell
New-PnPMicrosoft365Group -DisplayName $title -Description $description -MailNickname $nickname -CreateTeam -Force -Owners $defaultOwnerUPN
```

**Comment by erwinvanhunen** [comment]
Regarding the latest trace you shared: we wait up to a timeout period for the team to be created (1 minute). It seems that in your environment  it takes a long time to create a team. I will up the timeout period to 2 minutes now. That will be available in 1.2.19-nightly

**Comment by joelfmrodrigues** [comment]
@erwinvanhunen sorry for the delay to test this, multiple projects running...
Just tested with version 1.3.0 and can confirm that it's working! Takes a bit, but works :)
Closing item
Thank you!
