### ISSUE TITLE
[BUG] New-PnPSite: Microsoft Graph service exception when Owner parameter unresolvable

### ISSUE THREAD

**Issue by JaredRic-corp** [pnp/powershell#5006]
### Reporting an Issue or Missing Feature
While running New-PnPSite, if the -Owner parameter is specified with a value that cannot be resolved, the command silently continues past the resolve failure and tries to create the backing M365 group with a null owner value resulting in an error, no clear message to the user while it failed:

New-PnPSite: Microsoft Graph service exception

Example underlying HTTP requests:
**Request to resolve user and fail, nothing shown in PowerShell**
```
GET https://graph.microsoft.com/v1.0/users/nonexistent@contoso.com?$select=id
404 Not Found (application/json)
```

**Request to create group with an incomplete owner value**
```
POST https://graph.microsoft.com/v1.0/groups
{
 "displayName": "Marketing",
 "mailEnabled": true,
 "mailNickname": "Marketing",
 "visibility": "Private",
 "groupTypes": ["Unified"],
 ❌"owners@odata.bind": [],❌ 
 "securityEnabled": false,
 "resourceBehaviorOptions": [],
 "creationOptions": [
   "implicit_formula_292aa8a00786498a87a5ca52d9f4214a_00000000-0000-0000-0000-000000000000",
   "SPSiteLanguage:1033",
   "HubSiteId:00000000-0000-0000-0000-000000000000"
 ]
}

400 Bad Request (application/json)
{
  "error": {
    "code": "Request_BadRequest",
    "message": "The value of 'odata.bind' property annotation is an empty array. The 'odata.bind' property annotation must have a non-empty array as its value.",
    "innerError": {
      "date": "2025-07-10T16:53:06",
      "request-id": "00000000-0000-0000-0000-000000000000",
      "client-request-id": "00000000-0000-0000-0000-000000000000"
    }
  }
}
```

There are no issues if you either leave the Owner parameter off or you pass a null value to it, in those situations no owner property is passed in the graph call to create the group and the service automatically sets the user who connected as the owner.

### Expected behavior 
If the Owner property is specified but unresolvable, the command should fail with an informative message and skip attempts to create the backing M365 group.

### Actual behavior 
Receiving error: New-PnPSite: Microsoft Graph service exception

### Steps to reproduce behavior
1. Connect with PnP, I used delegated auth in my testing.
2. Run the New-PnPSite command with the -Owner parameter with an invalid value (user not in tenant, a group, etc)
`New-PnpSite -Type TeamSite -Title "Marketing" -Alias "marketing" -Owners "nonexistent@contoso.com"`

### What is the version of the Cmdlet module you are running?
Reproduced on:
- 3.1.78 nightly build
- 3.1.84 nightly build

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by JaredRic-corp** [comment]
Example of failure:

<img width="1103" height="188" alt="Image" src="https://github.com/user-attachments/assets/af76daa4-f297-4b12-8ad3-b6f037a1e853" />

**Comment by gautamdsheth** [comment]
hey @JaredRic-corp , thanks for raising this issue. We have improved the error message and it will show more details about the error. 
The fix is available starting with tomorrow's nightly builds as well as next major version when we release it.

**Comment by JaredRic-corp** [comment]
@gautamdsheth Thank you! The changes you made are helpful since it is now returning the graph error from the attempt to create the site with a null value, but the error message returned there still doesn't give the user knowledge of why it is failing requiring them to take a network trace, it also continues on to make the new group request even though we know it couldn't resolve the user.

<img width="1100" height="126" alt="Image" src="https://github.com/user-attachments/assets/4dc0f815-987a-40b1-8b12-00852d929961" />

`New-PnPSite -Type TeamSite -Title "Marketing" -Alias "marketing123123123" -Owners "NonExistent@contoso.com" -Verbose
VERBOSE: Cmdlet execution started for New-PnPSite -Type TeamSite -Title "Marketing" -Alias "marketing123123123" -Owners "NonExistent@contoso.com" -Verbose
New-PnPSite: Microsoft Graph service exception - Request_BadRequest 400 The value of 'odata.bind' property annotation is an empty array. The 'odata.bind' property annotation must have a non-empty array as its value.`

Can it validate if the call to resolve the user failed before attempting to create the group? That would give the user an actionable message and never attempt the additional request to create the group with a null value.

**Comment by gautamdsheth** [comment]
@JaredRic-corp  - we don't validate the users before. We only the surface the error that we get when we try to provision the site/group.

**Comment by JaredRic-corp** [comment]
@gautamdsheth thanks, I'm seeing that now! 

So to fix this with a valuable error message to the end users of PnP.PowerShell module it would need to be fixed in an underlying location like in PnPCore?

It looks like it would potentially be here: https://github.com/pnp/pnpcore/blob/bcca194f58f5853417dd47353140b87f40727e04/src/sdk/PnP.Core.Admin/Model/Microsoft365/Internal/Microsoft365Admin.cs#L247

```
// Prepare the group resource object
            if (graphGroupOptions.Owners != null && graphGroupOptions.Owners.Length > 0)
            {
                graphGroupOptions.Owners = (await ResolveUsersAsync(graphGroupOptions.Owners).ConfigureAwait(false)).ToArray();
            }
```
