### ISSUE TITLE
[BUG] Cannot successfully use Register-PnPManagementShellAccess (per instructions)

### ISSUE THREAD

**Issue by sympmarc** [pnp/powershell#66]
### Reporting an Issue or Missing Feature
Cannot successfully use `Register-PnPManagementShellAccess` per the instructions 

### Expected behavior 

@ToddKlindt and I were trying out the process of moving from `SharePointPnPPowerShellOnline` to `PnP.PowerShell`. We know it's still a bit early, but we like understanding new stuff. Once I got my machine set up with PowerShell 7 and had `PnP.PowerShell` installed, I tried `Connect-PnPOnline`, expecting it wouldn't work on the first try, as shown in VS Code here.

![image](https://user-images.githubusercontent.com/1295627/102927198-80028800-4464-11eb-9876-dcd0f8e004f5.png)

### Actual behavior 

As shown in the screenshot above, I ran `Register-PnPManagementShellAccess` to set things up. The browser window popped up, I logged in, the browser window closed itself, and things just sat where they were in the image. Todd tested in a shell and had the same problem.

Instead, Todd tried closing the automatic browser window and manually going to http://microsoft.com/devicelogin in a browser tab. Logging in there took us to the consent dialog and Parker's `PnP Management Shell` was installed in Enterprise Applications.
![image](https://user-images.githubusercontent.com/1295627/102929999-a24ad480-4469-11eb-9f6a-13e71afc083b.png)

### Steps to reproduce behavior
Run `Register-PnPManagementShellAccess` and follow the prompts in the popup browser window.

### What is the version of the Cmdlet module you are running?
0.3.14 nightly

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Interesting! Let me try to figure out what's going on here.

**Comment by erwinvanhunen** [comment]
Can you try removing the PnP Management Shell application from your Azure AD? (it's in enterprise applications) and try again? I just tried it here and had no issues, the whole flow went through as expected.

**Comment by sympmarc** [comment]
@ToddKlindt and I were testing things in two different tenants yesterday. His had the PnP Management Shell installed already, but mine didn't. We both saw the same outcome, but using different entry points - I was using VS Code and he was in a PowerShell shell.

I just deleted the PnP Management Shell from the tenant I'm using and ran through the process again, with the same results. Here are the detailed screenshots going through - though you know what they look like. At the end of the process, I'm not asked for consent - that screen just never comes up.

Run `Register-PnPManagementShellAccess`

![image](https://user-images.githubusercontent.com/1295627/103003739-5ba7b980-44ff-11eb-8fe8-948d054d9d90.png)

Browser pops up and I paste in the code

![image](https://user-images.githubusercontent.com/1295627/103003796-7843f180-44ff-11eb-8fa5-60f192ed12e8.png)

Asked for acccount

![image](https://user-images.githubusercontent.com/1295627/103004052-8e51b200-44ff-11eb-9e4b-e9445c408fc3.png)

Enter password

![image](https://user-images.githubusercontent.com/1295627/103004155-96115680-44ff-11eb-8591-ddf4081c6949.png)

Browser window closes and back to VS Code (just because it was in the background)

![image](https://user-images.githubusercontent.com/1295627/103004474-ade8da80-44ff-11eb-8362-7280710e70d6.png)

**Comment by sympmarc** [comment]
p.s. If I go to https://microsoft.com/devicelogin in a separate browser tab, I *do* get the consent pop up, and everything completes as expected, just like yesterday.

![image](https://user-images.githubusercontent.com/1295627/103006358-30719a00-4500-11eb-9ff1-0f72ef14e574.png)

**Comment by erwinvanhunen** [comment]
Right. Could you try again using the 'built-in flow', but while running fiddler? We monitor the urls that the popup/embedded browser is navigating you too and most likely we receive an URL making PnP PS think it can close the browser, basically before the consent occurs. A fiddler trace will help us understand what URL is being received (optionally share the trace privately with me).

**Comment by erwinvanhunen** [comment]
I tested it with a colleague who was able to reproduce it. I'm looking into a solution now.

**Comment by sympmarc** [comment]
Good to hear @ToddKlindt and I aren't crazy. Let us know if we can help somehow. Sorry I hadn't gotten to the Fiddler trace yet, but I can still do it if you need it.

**Comment by erwinvanhunen** [comment]
I actually made a change now where we do not automatically close the popup browser window when executing Register-PnPManagmentShellAccess. This will be available in the upcoming nightly release: 0.3.20-nightly.

**Comment by sympmarc** [comment]
Would you still like a Fidler trace?

**Comment by erwinvanhunen** [comment]
No, that's not needed anymore. Thanks anway :-)

**Comment by gautamdsheth** [comment]
Verified, fixed with the 3.20-nightly. 

@sympmarc or @toddKlindt - can you confirm as well ?

**Comment by qul-d** [comment]
> ### Reporting an Issue or Missing Feature
> Cannot successfully use `Register-PnPManagementShellAccess` per the instructions 
> 
> ### Expected behavior 
> 
> @ToddKlindt and I were trying out the process of moving from `SharePointPnPPowerShellOnline` to `PnP.PowerShell`. We know it's still a bit early, but we like understanding new stuff. Once I got my machine set up with PowerShell 7 and had `PnP.PowerShell` installed, I tried `Connect-PnPOnline`, expecting it wouldn't work on the first try, as shown in VS Code here.
> 
> ![image](https://user-images.githubusercontent.com/1295627/102927198-80028800-4464-11eb-9876-dcd0f8e004f5.png)
> 
> ### Actual behavior 
> 
> As shown in the screenshot above, I ran `Register-PnPManagementShellAccess` to set things up. The browser window popped up, I logged in, the browser window closed itself, and things just sat where they were in the image. Todd tested in a shell and had the same problem.
> 
> Instead, Todd tried closing the automatic browser window and manually going to http://microsoft.com/devicelogin in a browser tab. Logging in there took us to the consent dialog and Parker's `PnP Management Shell` was installed in Enterprise Applications.
> ![image](https://user-images.githubusercontent.com/1295627/102929999-a24ad480-4469-11eb-9f6a-13e71afc083b.png)
> 
> ### Steps to reproduce behavior
> Run `Register-PnPManagementShellAccess` and follow the prompts in the popup browser window.
> 
> ### What is the version of the Cmdlet module you are running?
> 0.3.14 nightly
> 
> ### Which operating system/environment are you running PnP PowerShell on?
> - [x] Windows
> - [ ] Linux
> - [ ] MacOS
> - [ ] Azure Cloud Shell
> - [ ] Azure Functions
> - [ ] Other : please specify

**Comment by ComputerHabit2** [comment]
I'm stuck in a loop trying to get managment shell to work.  It won't work.  I don't get registration prompt.  I just get an error that the app isn't registered.  I deleted the existing one but the error persists.

**Comment by ToddKlindt** [comment]
> I'm stuck in a loop trying to get managment shell to work. It won't work. I don't get registration prompt. I just get an error that the app isn't registered. I deleted the existing one but the error persists.

This has changed a bunch since this discussion. [Read this thread ](https://github.com/pnp/powershell/issues/4250)to see what's changed and what you need to do now.

**Comment by ComputerHabit2** [comment]
> I'm stuck in a loop trying to get managment shell to work. It won't work. I don't get registration prompt. I just get an error that the app isn't registered. I deleted the existing one but the error persists.

AADSTS700016: Application with identifier '31359c7f-bd7e-475c-86db-fdb8c937548e' was not found in the directory 'company'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by ComputerHabit2** [comment]
> > I'm stuck in a loop trying to get managment shell to work. It won't work. I don't get registration prompt. I just get an error that the app isn't registered. I deleted the existing one but the error persists.
> 
> This has changed a bunch since this discussion. [Read this thread ](https://github.com/pnp/powershell/issues/4250)to see what's changed and what you need to do now.

I just read the article.  I think I'd read it before.

The command Register-PnPManagementShellAccess is no longer functional correct?

I should be creating my own Application.  
Maybe using the Register-PnPEntraIDApp command.  That did seem to work.

The only issue I have right now is I was trying to actually Register-PnPEntraIDApp  and then provide permissions.

When I ran Grant-PnPAzureADAppSitePermission it said I need to use -PnPManagementShell to make the change.

**Comment by sympmarc** [comment]
I'd recommend setting up the app registration manually, as outlined here: https://pnp.github.io/powershell/articles/registerapplication.html
This way, you can consent to the permissions you specifically need to run your PnP.PowerShell scripts.

**Comment by ComputerHabit2** [comment]
> I'd recommend setting up the app registration manually, as outlined here: https://pnp.github.io/powershell/articles/registerapplication.html This way, you can consent to the permissions you specifically need to run your PnP.PowerShell scripts.

Ugg.... I so wanted to use the new commands.  I've invested so much time into trying to learn this stuff and boooo...

**Comment by ComputerHabit2** [comment]
Also I have the app and full control and all the permissions and still commands fail.  

I'm on to hoping now Install-Module -Name PnP.PowerShell -AllowPrerelease will fix it.

**Comment by ComputerHabit2** [comment]
> Also I have the app and full control and all the permissions and still commands fail.
> 
> I'm on to hoping now Install-Module -Name PnP.PowerShell -AllowPrerelease will fix it.

NOPE
Install-Package: The version '2.12.18' of the module 'PnP.PowerShell' being installed is not catalog signed. Ensure that the version '2.12.18' of the module 'PnP.PowerShell' has the

**Comment by sympmarc** [comment]
I

> > I'd recommend setting up the app registration manually, as outlined here: https://pnp.github.io/powershell/articles/registerapplication.html This way, you can consent to the permissions you specifically need to run your PnP.PowerShell scripts.
> 
> Ugg.... I so wanted to use the new commands. I've invested so much time into trying to learn this stuff and boooo...

If you're a Gloabl Admin, the new cmdlets should work for you - if you've upgraded to PnP.PowerShell 2.12+.

**Comment by ComputerHabit2** [comment]
> I don't see a question at that link. Can you be more specific about what you've done and what error(s) you're getting?

I'm having a bad day :)
https://github.com/pnp/powershell/discussions/4351

Wrong url in my clip board.
