### ISSUE TITLE
[BUG] Get-PnPTenantSite: The property or field 'AuthContextStrength' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

### ISSUE THREAD

**Issue by klaaslauwers** [pnp/powershell#927]
I don't know since when exactly, but recently the command `Get-PnPTenantSite` started failing with the following error: 
The property or field 'AuthContextStrength' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

I have not changed anything in my PS script, nor did I update my PnP.PowerShell module.

### Expected behavior 
`Get-PnPTenantSite` should return the tenant site as expected.

### Actual behavior 
![image](https://user-images.githubusercontent.com/23431246/126295773-f64c997a-a2b1-43c6-bda8-0a883cb14425.png)

### Steps to reproduce behavior
```
Connect-PnPOnline -Url $variables.Get_Item("AdminUrl") -ClientId $variables.Get_Item("AppClientId") -Tenant $variables.Get_Item("TenantName") -CertificatePath "$($variables.Get_Item("CertificatePath"))" -CertificatePassword $certificatePassword -ErrorAction Stop
Get-PnPTenantSite -Identity "[site url here]" -Detailed
```
Even without the detailed switch, the same error is thrown.

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by kloosterj** [comment]
Same issue here, started yesterday afternoon CET.

**Comment by paololec** [comment]
Same issue.

**Comment by klaaslauwers** [comment]
@erwinvanhunen - Any idea why this command fails? Sorry to PM you, but this is quite blocking for our customers :-(

**Comment by ilionxedekeijzer** [comment]
Same here, from Powershell on my own PC with interactive logon as well as an Azure Automation runbook which is using certificate based logon.

**Comment by johannes-baldinger** [comment]
Same here. This Issue seems to be solved by this commit: https://github.com/pnp/powershell/commit/22985f6f3d15c0d23919a24288d7f92a175c2ab9.

**Comment by fikryGaf** [comment]
it's still giving the same error. it's totally immature and annoying and unprofessional to to such behaviour and cause many vital businesses to fail to be stopped suddenly without any rational ! 

  … terSPList = Get-PnPTenantSite  -Detailed -Filter  "Url -like 'https:/ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property or field 'AuthContextStrength' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

**Comment by fikryGaf** [comment]
![image](https://user-images.githubusercontent.com/20460241/126358034-12e860a6-a286-4e1f-b0d7-b79b6740bc19.png)

**Comment by hicotton02** [comment]
same issue:
[DBG]: PS C:\Users\xxxx> Get-PnPTenantSite -Url $siteUrl    

Get-PnPTenantSite : The property or field 'AuthContextStrength' has not been initialized. It has not been requested or the request has not been executed. It may need to be 
explicitly requested.
At line:1 char:1
+ Get-PnPTenantSite -Url $siteUrl
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPTenantSite], PropertyOrField

**Comment by veronicageek** [comment]
@fikryGaf - I'm gonna stop you right there. 

> it's totally immature and annoying and unprofessional to to such behaviour and cause many vital businesses to fail to be stopped suddenly without any rational !

First, in case you didn't know, this is a **Community driven repository**. This means that we do that on our **personal time**, and we also have day jobs.

Second, this command is using CSOM in the background, which is not something we - as repo maintainers - are creating. If you have any complaints, please redirect them to Microsoft directly.

Third, a fix has been committed today by @erwinvanhunen & @gautamdsheth, and will be available with the `-nightly` release tomorrow. Not sure you'll find a plethora of repos with the same turnaround.

And finally, just in case this is still not fast enough for you, you have other alternatives like CSOM or the SharePoint Management Shell.

Hope it clarifies expectations.

**Comment by kpinel** [comment]
Still the same issue, unfortunately
```powershell
Get-PnPTenantSite : The property or field 'AuthContextStrength' has not been initialized. It has not been requested or
the request has not been executed. It may need to be explicitly requested.
At line:1 char:1
+ Get-PnPTenantSite -Identity "https://tenant.sharepoint.com/team ..."
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPTenantSite], PropertyOrFieldNotInitializedException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.GetTenantSite
PS C:\Users\xxx> Get-Module PnP.PowerShell

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.6.43     PnP.PowerShell                      {Add-PnPAlert, Add...
```
Also logging a job with MS

**Comment by sathya-bhat** [comment]
> Still the same issue, unfortunately
> 
> ```powershell
> Get-PnPTenantSite : The property or field 'AuthContextStrength' has not been initialized. It has not been requested or
> the request has not been executed. It may need to be explicitly requested.
> At line:1 char:1
> + Get-PnPTenantSite -Identity "https://tenant.sharepoint.com/team ..."
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [Get-PnPTenantSite], PropertyOrFieldNotInitializedException
>     + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.GetTenantSite
> PS C:\Users\xxx> Get-Module PnP.PowerShell
> 
> ModuleType Version    Name                                ExportedCommands
> ---------- -------    ----                                ----------------
> Manifest   1.6.43     PnP.PowerShell                      {Add-PnPAlert, Add...
> ```
> 
> Also logging a job with MS

@kpinel , the build 1.6.43 does not contain Eric's fix (9 hours ago) https://github.com/pnp/powershell/commit/22985f6f3d15c0d23919a24288d7f92a175c2ab9
. We may need to wait for tonight's build?

**Comment by kloosterj** [comment]
Confirmed, issue resolved after installing 1.6.44-nightly, using
Install-Module -Name PnP.PowerShell -AllowPrerelease -Force -SkipPublisherCheck

**Comment by gautamdsheth** [comment]
Closing this issue, if you are facing this error please update to the latest `1.6.44-nightly` .

**Comment by BaronSparky** [comment]
Awesome job.. Thanks team...

**Comment by mliben** [comment]
I second the Awesome Job! Downloaded the update and it is now working as expedcted.

Kudos (and much appreciated)

**Comment by klaaslauwers** [comment]
The fix did solve the issue for Get-PnPTenantSite, but it now throws an error on Invoke-PnPSiteTemplate further on in the code :-(. Thanks for the replies and the quick solution - but the problem shifted towards another command.

**Comment by sathya-bhat** [comment]
@klaaslauwers Is a bug open for Invoke-PnPSiteTemplate ?

**Comment by klaaslauwers** [comment]
@sathya-bhat Nah, I have solved the issue myself. Apparently, there is something wrong with the SupportedUILanguages handler in the template. So I just added -ExcludeHandlers SupportedUILanguages at the end of the command and disabled the multilingual features manually afterwards through:
`                        $Web = Get-PnPWeb -Includes IsMultilingual -Connection $newSiteConnection
                        $Web.IsMultilingual = $false
                        $Web.Update()
                        Invoke-PnPQuery`
